<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenUtau\OpenUtau.csproj" />
    <ProjectReference Include="..\OpenUtau.Core\OpenUtau.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <Target Name="CopyOutput" AfterTargets="Publish">
    <Move
      SourceFiles="$(PublishDir)\OpenUtauDRPC.dll;$(PublishDir)\DiscordRPC.dll"
      DestinationFolder="$(OutputPath)/OpenUtauDRPC" />
  </Target>

</Project>
